# Generated by Django 3.2.23 on 2023-11-10 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('pembelian_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waktu_pembelian', models.DateTimeField(auto_now_add=True)),
                ('status_pembelian', models.CharField(choices=[('belum_bayar', 'Belum bayar'), ('dikirim', 'Dikirim'), ('selesai', 'Selesai')], default='belum_bayar', max_length=20)),
                ('total_harga_pembelian', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('produk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=200)),
                ('deskripsi_produk', models.TextField(blank=True, null=True)),
                ('harga_produk', models.IntegerField()),
                ('kategori_produk', models.CharField(max_length=200)),
                ('gambar_produk', models.ImageField(blank=True, null=True, upload_to='produk/')),
            ],
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('pengiriman_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metode_pengiriman', models.CharField(max_length=20)),
                ('alamat_pengiriman', models.TextField()),
                ('status_pengiriman', models.CharField(default='pending', max_length=20)),
                ('no_resi', models.CharField(blank=True, max_length=255, null=True)),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pembelian')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('pembayaran_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_bank', models.CharField(max_length=20)),
                ('status_pembayaran', models.CharField(default='pending', max_length=20)),
                ('waktu_pembayaran', models.DateTimeField(auto_now_add=True)),
                ('no_va', models.CharField(blank=True, max_length=255, null=True)),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pembelian')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kuantitas', models.IntegerField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('total_harga_item', models.IntegerField()),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pembelian')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.produk')),
            ],
        ),
    ]
