# Generated by Django 3.2.23 on 2023-11-09 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_pembelian', models.DateTimeField(auto_now_add=True)),
                ('status_pembelian', models.CharField(default='pending', max_length=20)),
                ('total_harga_pembelian', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=200)),
                ('deskripsi_produk', models.TextField()),
                ('harga_produk', models.IntegerField()),
                ('kategori_produk', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode_pengiriman', models.CharField(max_length=20)),
                ('alamat_pengiriman', models.TextField()),
                ('status_pengiriman', models.CharField(default='pending', max_length=20)),
                ('no_resi', models.CharField(blank=True, max_length=255, null=True)),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pembelian')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bank', models.CharField(max_length=20)),
                ('status_pembayaran', models.CharField(default='pending', max_length=20)),
                ('waktu_pembayaran', models.DateTimeField(auto_now_add=True)),
                ('no_va', models.CharField(blank=True, max_length=255, null=True)),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pembelian')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.IntegerField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('total_harga_item', models.IntegerField()),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pembelian')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.produk')),
            ],
        ),
    ]
