# Generated by Django 3.2.23 on 2023-11-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='deskripsi_produk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
