# Generated by Django 3.2.23 on 2023-11-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231111_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='stok_produk',
            field=models.CharField(choices=[('tersedia', 'Tersedia'), ('habis', 'Habis')], default='tersedia', max_length=200),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='status_pembayaran',
            field=models.CharField(default='belum_bayar', max_length=20),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='status_pembelian',
            field=models.CharField(choices=[('belum_bayar', 'Belum bayar'), ('dikirim', 'Dikirim'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='belum_bayar', max_length=20),
        ),
        migrations.AlterField(
            model_name='pengiriman',
            name='metode_pengiriman',
            field=models.CharField(choices=[('jne', 'JNE'), ('ambil_sendiri', 'Ambil sendiri')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pengiriman',
            name='status_pengiriman',
            field=models.CharField(choices=[('belum_dikirim', 'Belum dikirim'), ('dikirim', 'Dikirim'), ('diterima', 'Diterima')], default='belum_dikirim', max_length=20),
        ),
        migrations.AlterField(
            model_name='produk',
            name='kategori_produk',
            field=models.CharField(choices=[('komputer', 'Komputer'), ('hardware', 'Hardware'), ('aksesoris', 'Aksesoris')], default='hardware', max_length=200),
        ),
    ]
