# Generated by Django 3.2.23 on 2023-11-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_produk_deskripsi_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar_produk',
            field=models.ImageField(blank=True, null=True, upload_to='produk/'),
        ),
    ]
