# Generated by Django 3.2.23 on 2023-11-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_produk_kategori_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='waktu_pembelian',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
