# Generated by Django 3.2.23 on 2023-11-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_pembelian_waktu_pembelian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='status_pembayaran',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='is_bayar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='waktu_pembayaran',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='status_pembelian',
            field=models.CharField(choices=[('keranjang', 'Keranjang'), ('belum_bayar', 'Belum bayar'), ('diproses', 'Diproses'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='keranjang', max_length=20),
        ),
    ]
