# Generated by Django 3.2.23 on 2023-11-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20231111_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='waktu_kedaluarsa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
