# Generated by Django 3.2.23 on 2023-11-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_pembayaran_waktu_kedaluarsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='transaksi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
