# Generated by Django 3.2.23 on 2023-11-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_pembayaran_waktu_kedaluarsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='is_bayar',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='status_pembayaran',
            field=models.CharField(default='belum_bayar', max_length=20),
        ),
    ]
