# Generated by Django 3.2.23 on 2023-11-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20231112_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengiriman',
            name='alamat_pengiriman',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pengiriman',
            name='status_pengiriman',
            field=models.CharField(choices=[('belum_dikirim', 'Belum dikirim'), ('belum_diambil', 'Belum diambil'), ('dikirim', 'Dikirim'), ('diterima', 'Diterima')], max_length=20),
        ),
    ]
