# Generated by Django 3.2.23 on 2023-11-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20231112_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='status_pembayaran',
            field=models.CharField(choices=[('belum_bayar', 'Belum bayar'), ('kadaluarsa', 'Kadaluarsa'), ('dibayar', 'Dibayar')], default='belum_bayar', max_length=20),
        ),
    ]
