# Generated by Django 3.2.23 on 2023-11-12 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_pembayaran_status_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengiriman',
            name='pembelian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.pembelian'),
        ),
    ]
