# Generated by Django 3.2.23 on 2023-11-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_pengiriman_pembelian'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengiriman',
            name='ongkos_kirim',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produk',
            name='berat_produk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
