# Generated by Django 3.2.23 on 2023-11-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20231112_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='total_pembayaran',
            field=models.IntegerField(default=0),
        ),
    ]
