# Generated by Django 3.2.23 on 2023-11-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_pembayaran_total_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='total_pembayaran',
            field=models.IntegerField(),
        ),
    ]
