# Generated by Django 3.2.23 on 2023-11-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_pembayaran_total_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='status_pembayaran',
            field=models.CharField(choices=[('belum_bayar', 'Belum bayar'), ('kadaluarsa', 'Kadaluarsa'), ('dibayar', 'Dibayar'), ('dibatalkan', 'Dibatalkan')], default='belum_bayar', max_length=20),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='total_pembayaran',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
