# Generated by Django 3.2.23 on 2023-11-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_pengiriman_status_pengiriman'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelian',
            name='total_berat',
            field=models.IntegerField(default=0),
        ),
    ]
