# Generated by Django 3.2.23 on 2023-11-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_pembelian_total_berat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengiriman',
            name='nama_penerima',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='no_telp_penerima',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
