# Generated by Django 3.2.23 on 2023-11-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20231114_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='total_pembayaran',
            field=models.IntegerField(default=0),
        ),
    ]
