# Generated by Django 3.2.23 on 2023-11-14 10:58

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_pembayaran_total_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(default=base.models.generate_item_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='pembayaran_id',
            field=models.CharField(default=base.models.generate_pembayaran_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='pembelian_id',
            field=models.CharField(default=base.models.generate_pembelian_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pengiriman',
            name='pengiriman_id',
            field=models.CharField(default=base.models.generate_pengiriman_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produk',
            name='produk_id',
            field=models.CharField(default=base.models.generate_produk_id, max_length=20, primary_key=True, serialize=False),
        ),
    ]
