# Generated by Django 3.2.23 on 2023-11-14 11:34

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20231114_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(default=base.models.generate_item_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='pembayaran_id',
            field=models.CharField(default=base.models.generate_pembayaran_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='pembelian_id',
            field=models.CharField(default=base.models.generate_pembelian_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='status_pembelian',
            field=models.CharField(choices=[('keranjang', 'Keranjang'), ('menunggu', 'Menunggu'), ('diproses', 'Diproses'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='keranjang', max_length=20),
        ),
        migrations.AlterField(
            model_name='pengiriman',
            name='pengiriman_id',
            field=models.CharField(default=base.models.generate_pengiriman_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produk',
            name='produk_id',
            field=models.CharField(default=base.models.generate_produk_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
